### ISSUE TITLE
how long and how much

### ISSUE THREAD

**Issue by vosaul** [adamdjbrett/lyons-1#3]
@adamdjbrett 

Hello Adam,
do you have an Upwork account?
It's easier for me to work with an hourly rate. Unfortunately, there is no such possibility on Fiverr.
My Upwork account https://www.upwork.com/o/profiles/users/~01e15a95b688533fec/

**Comment by adamdjbrett** [comment]
I have not heard of this service I will see about getting setup here. thank you
